comment:
  content:
    max_length: 160
post:
  content:
    max_length: 1024
user:
  edit:
    start_year: 1970
  full_name:
    max_length: 50
  password:
    min_length: 6
  user_name:
    max_length: 20
    min_length: 5
